name: Create Application

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Nome do novo projeto'
        required: true
      project_type:
        description: 'Tipo de aplicação'
        required: true
        type: choice
        options:
          - Backend - Python
          - Frontend - Angular Shell
          - Frontend - Angular MFE

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Definir variáveis
        run: |
          echo "WORKFLOW_VERSION=v1" >> $GITHUB_ENV
          echo "INPUT_PROJECT_NAME=${{ github.event.inputs.project_name }}" >> $GITHUB_ENV
          
          PROJECT_TYPE="frontend"

          if [[ "$INPUT_PROJECT_NAME" == *Python ]]; then
            PROJECT_TEMPLATE="StackSpot-Application-Python"
            PROJECT_TYPE="backend"
          elif [[ "$INPUT_PROJECT_NAME" == *Angular\ Shell ]]; then
            PROJECT_TEMPLATE="StackSpot-Application-Angular-Shell"
          elif [[ "$INPUT_PROJECT_NAME" == *Angular\ MFE ]]; then
            PROJECT_TEMPLATE="StackSpot-Application-Angular-MFE"
          else
            echo "Tipo de aplicação inválido: ${{ env.PROJECT_TYPE }}"
            exit 1
          fi

          echo "PROJECT_TEMPLATE=$PROJECT_TEMPLATE" >> $GITHUB_ENV
          echo "PROJECT_TYPE=v$PROJECT_TYPE" >> $GITHUB_ENV
          echo "PROJECT_NAME=gen-$WORKFLOW_VERSION-$REPO_TYPE-$INPUT_PROJECT_NAME" >> $GITHUB_ENV

      - name: Criar repositório via API
        run: |

          echo "NOME DO REPO: $PROJECT_NAME"

          curl -X POST \
            -H "Authorization: token ${{ secrets.TEMPLATE_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/user/repos \
            -d "{\"name\":\"$REPO_NAME\", \"private\":false}"

      - name: Clonar template correspondente
        run: |

          echo "Clonando template: $PROJECT_TEMPLATE para o repositório $PROJECT_NAME..."
          git clone https://$TEMPLATE_TOKEN@github.com/$PROJECT_TEMPLATE.git temp
          
          cd temp
          git remote remove origin
          git remote add origin https://github.com/GTotonio/$PROJECT_NAME.git
          git push -u origin main
